services:
  frontend:
    build: ./gashtemoon-front
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./gashtemoon-back
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - app-network

  panel:
    build: 
      context: ./gashtemoon-panel
      args:
          REACT_APP_BASE_API: "http://api.gashtemoon.it"
    ports:
      - "4000:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8087:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/gashtemoon.ir.crt:/etc/nginx/ssl/gashtemoon.ir.crt
      # - ./nginx/gashtemoon.ir.key:/etc/nginx/ssl/gashtemoon.ir.key
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    extra_hosts:
      - "gashtemoon.it:192.168.80.210"

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
    
