/* eslint-disable no-dupe-keys */
const en = {
  Menu: {
    SiteInfo: "SiteInfo",
    Suppliers: "Suppliers",
    Services: "Services",
    Blog: "Blog",
    Comments: "Comments",
    Notifications: "Notifications",
    Messages: "Messages",
    Managers: "Managers",
    Galleries: "Galleries",
    Branches: "Branches",
  },

  Login: {
    mobile: "Phone Number",
    password: "Password",
    btn: "Signin",
  },

  top_menu: {
    gallery: "Gallery",
    provinces: "Provinces",
    counties: "Counties",
    attractionType: "Attraction Type",
    genders: "Genders",
    home: "Home",
    blog: "Blog",
    map: "Map",
    users: "Users",
    timeline: "Time Line",
    comments: "Comments",
    changeRoleRequests: "Change Role Requests",
    reports: "Reports",
    aboutus: "About Us",
    contactus: "Contact Us",
    attractions: "Attractions",
    posts: "Posts",
  },

  map: {
    select: "Select",
    provincename: "Province",
    countyname: "County",
    attractionType: "Type",
    mainInfo: "Main Info",
    introduction: "Introduction",
    addPost: "Add Post",
    addAttraction: "Add Attraction",
    addAttractionForOtherLangs: "Add Attraction for other languages",
    addBlog: "Add Blog",
    addOrEdit: "Add/Edit",
    delete: "Delete",
    edit: "Edit",
    title: "Title",
    website: "Website",
  },

  editor: {
    title: "Title",
    caption: "Caption",
  },

  SiteInfo: {
    navbar: "NavBar",
    slides: "Slides",
    statistics: "Slides",
    footer: "Footer",
    contact: "Contact Details",
    phones: "Phones",
    emails: "Emails",
    address: "Address",
    selectLocation: "Select Location on map",
    uploadFile: "Upload File",
    title: "Title",
    value: "Value",
    description: "Description",
    confirm: "Confirm",
  },

  attrType: {
    name: "Attravtion Type",
  },
  sites: {
    daya: "Daya",
  },

  Comments: {
    user: "user",
    comment: "text",
    postorcourse: "post/course",
    activeDeactive: "activ/deactive",
    delete: "delete",
    submit: "submit",
    active: "active",
    name: "Name",
    email: "Email",
  },

  TimeLine: {
    from: "From",
    to: "To",
    durationType: "Type",
    addBranch: "Add Dynasty",
    addOrEdit: "Add/Edit",
    delete: "Delete",
    edit: "Edit",
    title: "attraction Title",
    phones: "cover",
    address: "Address",
    location: "Location",
    stafs: "Stafs",
    stafName: "Staf Name",
    stafTitle: "Staf Title",
  },

  blog: {
    addBlog: "Add Blog",
    addPost: "Add Post",
    addOrEdit: "Add/Edit",
    delete: "Delete",
    edit: "Edit",
    title: "Title",
    type: "Post Type",
    site: "Site",
    videoLink: "Video Link",
    podcastLink: "Podcast Link",
    video: "video",
    podcast: "podcast",
    text: "text",
    blogType: "Blog",
    postType: "Post",
    yes: "Yes",
    no: "No",
    delete_province: "",
    delete_county: "",
    delete_comment: "",
    delete_request: "",
    delete_attType: "",
    delete_post: "",
    delete_attraction: "",
    delete_slide: "",
  },

  requests: {
    mobile: "Mobile No",
    nationalCode: "National Code",
    userType: "User Type",
    reqType: "Change role to",
    file: "فایل",
    description: "توضیحات",
  },

  leaders: {
    nature: "Natural Guide",
    culture: "Cultural Guide",
  },

  Notifications: {
    text: "text",
    activeDeactive: "active/deactive",
    edit: "edit",
    delete: "delete",
    addoredit: "Add/Edit",
    active: "activate",
    deactive: "deactivate",
  },

  Messages: {
    mobile: "mobile / Email",
    title: "title",
    description: "description",
  },

  Managers: {
    addorEdit: "Add/Edit",
    resume: "English Resume",
    name: "name",
    edit: "edit",
    delete: "delete",
    title: "Title",
  },

  Gallery: {
    title: "Title",
    image: "Image",
    link: "Link",
    type: "Type",
    add: "Add",
  },

  User: {
    delete_user: "Delete User",
    name: "User Title",
    active_inactive: "Active/Inactive",
    group: "Group",
    role: "Role",
    admin_role: "Admin",
    culture_guide_role: "Culture Guide",
    nature_guide_role: "Nature Guide",
    user_role: "User",
    addUser: "Add User",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    password: "Password",
    onQuoteDescription: "OneQuoteDescription",
    addProvince: "Add User",
    addGender: "Add Gender",
    addCounty: "Add User",
    addAttractionType: "Add Attraction Type",
  },

  editor: {
    title: "Title",
    paragraph: "Paragraph",
    image: "Image",
    audio: "Audio",
    video: "Video",
    quote: "Quote",
    seoarator: "Separator",
  },
};
export default en;
