module.exports = {
  InactiveUserError: "Der Benutzer ist inaktiv",
  serverErrorMessage: "Serverfehler",
  mobileOrEmailErrorMessage: "E-mail oder Handynummer ist falsch",
  nameErrorMessage: "Name ist erforderlich",
  passwordErrorMessage: "Das Passwort muss mindestens 6 zeichen sein",
  mobileOrEmailExistErrorMessage: "Die eingegebene E-mail oder Handynummer wurde bereits verwendet",
  unAuthorizeErrorMessage: "Fehler beim suchen des Benutzers",
  expiredCodeError: "Der code ist abgelaufen",
  inCorrectCode: "Der eingegebene Code ist falsch",
  userNotExist: "Es gibt keinen Benutzer mit diesem Profik",
  SuccessLoginMessage: "Die Anmeldung war erfolgreich",
  SuccessLogoutMessage: "Die Abmeldung war erfolgreich",
  uploadSuccessMessage: "Der Upload war erfolgreich",
  SuccessSave: "Mission erfüllt",
  SendMessageSuccessfull: "Ihre Nachricht wurde erfolgreich gesendet",
  LikeExists: "شما قبلا این پست را پسندیده اید!",
  SaveExists: "Sie haben diesen Post bereits gespeichert",
  FollowerExists: "Sie sind diesem Benutzer bereits gefolgt",
  RequestExists: "Request already sent. please wait",
};
