module.exports = {
  InactiveUserError: "User is not Active",
  serverErrorMessage: "server error",
  mobileOrEmailErrorMessage: "mobileOrEmail invalid",
  mobileOrEmailExistErrorMessage: "mobile or email exist",
  unAuthorizeErrorMessage: "unAuthorizeErrorMessage",
  expiredCodeError: "expiredCodeError",
  inCorrectCode: "inCorrectCode",
  passwordErrorMessage: "password invalid",
  nameErrorMessage: "name invalid",
  userNotExist: "userNotExist",
  SuccessLoginMessage: "login Successfull",
  SuccessLogoutMessage: "logout Successfull",
  uploadSuccessMessage: "upload Successfull",
  SuccessSave: "Successfull!",
  SendMessageSuccessfull: "Message sent successfully!",
  LikeExists: "You already liked this post!",
  SaveExists: "You already saved this post!",
  FollowerExists: "You already followed this user!",
  RequestExists: "Request already sent. please wait",
  RequestddExists: "Request already sent. please wait",

};
